tag: VesselMeshSegmentation-SAME-TIME

network:
  use_cuda: true
  use_parallel: false
  modules:
    Unet:
      defin_path: ./mtools/mtorch/models/Unet3D.py
      defin_parm: {in_channels: 1, out_channels: 1, channels: [64, 128, 256]}
      cur_params: &cur_params './checkpoints-graph/Tag-VesselMeshSegmentation-GCN-best-checkpoint.pth'

    Gseg:
      defin_path: ./models/GraphSeg.py
      defin_parm: {coords_dim: 3, hidden_dim: 192, feats_dims: [128, 64, 32]}
      cur_params: *cur_params

