tag: Unet

dataset:
  defin_path: ./dataset.py
  defin_parm: {}
  batch_size: 256
  num_worker: 64
  isdroplast: false
  is_shuffle: true
  defin_sampler: null
  param_sampler: {}

network:
  use_cuda: true
  use_parallel: false
  modules:
    Unet:
      defin_path: ./mtools/mtorch/models/Unet3D.py
      defin_parm: {in_channels: 1, out_channels: 1, channels: [64, 128, 256]}
      cur_params: &cur_params null
      int_method: &int_method kaiming
      optimizers: &optimizers {type: Adam, lr: 0.001, cur_params: *cur_params}
      schedulers: &schedulers {type: ReduceLROnPlateau, mode: max, factor: 0.1, patience: 10, cur_params: *cur_params}


  criterions:
    Imageloss:
      defin_path: ./models/ImageLoss.py
      defin_parm: {}
      weight: 1

trainer:
  checkpoint_mode: {dire: ./checkpoints-st, type: key_epoch}
  #  checkpoint_mode: {dire: ./checkpoints, type: all_epoch}
  validation_step: 1
  threshold_grad: 1e5
  total_epoches: 1000
  current_epoch: 1


monitor:
  index: chamfer
  logger: true
  stdstream: true
  tensorboardx: true